export const japaneseLabels: Record<string, string> = {
  Bookmarks: "ブックマーク",
  Downloads: "ダウンロード",
  History: "履歴",
  Settings: "設定",
  Debug: "デバッグ",
  "New Tab": "新しいタブ",
  "Search or enter URL": "検索語句またはURLを入力",
  "No bookmarks": "ブックマークはまだありません",
  "No downloads": "ダウンロードはまだありません",
  "No history": "履歴はまだありません",
  Delete: "削除",
  Remove: "削除",
  Open: "開く",
  Reveal: "Finderで表示",
  "Clear downloads": "ダウンロード履歴を消去",
  "Search history": "履歴を検索",
  "Clear last hour": "直近1時間を消去",
  "Clear today": "今日の履歴を消去",
  "Clear all": "すべて消去",
  Earlier: "以前",
  General: "一般",
  Appearance: "外観",
  Language: "言語",
  Tabs: "タブ",
  Windows: "ウィンドウ",
  Search: "検索",
  Privacy: "プライバシー",
  Developer: "開発",
  "Downloads section": "ダウンロード",
  "Search settings": "設定を検索",
  System: "システム設定",
  Light: "ライト",
  Dark: "ダーク",
  English: "英語",
  Japanese: "日本語",
  "New tab": "新しいタブ",
  "Restore previous session": "前回のセッションを復元",
  "Home page": "ホームページ",
  "Home page URL": "ホームページURL",
  Save: "保存",
  Reset: "リセット",
  "Show sidebar": "サイドバーを表示",
  "Hide sidebar": "サイドバーを隠す",
  "Sidebar width": "サイドバー幅",
  "Reset sidebar width": "サイドバー幅をリセット",
  "Blank new tab": "空の新規タブ",
  "Home on new tab": "新規タブでホームを開く",
  "Default zoom level": "既定の表示倍率",
  "Ask before download": "保存前に確認",
  "Download automatically": "自動でダウンロード",
  "Download directory": "ダウンロード先",
  "Open DevTools": "DevToolsを開く",
  "Debug page": "デバッグページ",
  "Profile path": "プロファイルパス",
  "Windows and tabs": "ウィンドウとタブ",
  "Registered commands": "登録済みコマンド",
  "Recent events": "最近のイベント",
  Logs: "ログ",
  Actions: "操作",
  Completed: "完了",
  Starting: "開始中",
  Downloading: "ダウンロード中",
  Failed: "失敗",
  Canceled: "キャンセル済み",
  Permissions: "権限",
  "Permission decisions": "権限の決定",
  Camera: "カメラ",
  Microphone: "マイク",
  Location: "位置情報",
  Notifications: "通知",
  "Pointer lock": "ポインターロック",
  "Keyboard lock": "キーボードロック",
  Allow: "許可",
  Block: "ブロック",
  "Loading…": "読み込み中…",
  Reload: "再読み込み",
  "No results": "該当する項目はありません",
  "Could not load this page. Please try again.":
    "ページを読み込めませんでした。再試行してください。",
  "Custom search URL": "カスタム検索URL",
  "Settings sections": "設定項目",
  Shortcuts: "ショートカット",
  "No saved permission decisions.": "保存された権限の設定はありません。",
};
