if(NOT DEFINED APP_BUNDLE)
  message(FATAL_ERROR "APP_BUNDLE is required")
endif()

set(CONTENTS "${APP_BUNDLE}/Contents")
if(NOT EXISTS "${CONTENTS}/Resources/ui/index.html")
  message(FATAL_ERROR "UI assets are missing from the application bundle")
endif()
if(NOT IS_DIRECTORY "${CONTENTS}/Frameworks/Chromium Embedded Framework.framework")
  message(FATAL_ERROR "CEF framework is missing from the application bundle")
endif()
file(GLOB HELPERS "${CONTENTS}/Frameworks/Fubuki Browser Alpha Helper*.app")
if(NOT HELPERS)
  message(FATAL_ERROR "CEF helper applications are missing from the application bundle")
endif()
