set(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(PLIST_TEMPLATE "${REPOSITORY_ROOT}/native/resources/Info.plist.in")
set(ICONS_SOURCE "${REPOSITORY_ROOT}/icons/fubuki.icns")
set(ICONS_BUNDLE "${REPOSITORY_ROOT}/native/resources/fubuki.icns")

foreach(required_file IN ITEMS "${PLIST_TEMPLATE}" "${ICONS_SOURCE}" "${ICONS_BUNDLE}")
  if(NOT EXISTS "${required_file}")
    message(FATAL_ERROR "Required app icon file is missing: ${required_file}")
  endif()
endforeach()

file(READ "${PLIST_TEMPLATE}" plist_contents)
if(plist_contents MATCHES "<key>CFBundleIconName</key>")
  message(FATAL_ERROR "Info.plist must not reference an Asset Catalog icon without an Asset Catalog")
endif()
if(NOT plist_contents MATCHES "<key>CFBundleIconFile</key>[ \t\r\n]+<string>fubuki</string>")
  message(FATAL_ERROR "Info.plist must reference the fubuki.icns bundle resource")
endif()

file(SHA256 "${ICONS_SOURCE}" source_hash)
file(SHA256 "${ICONS_BUNDLE}" bundle_hash)
if(NOT source_hash STREQUAL bundle_hash)
  message(FATAL_ERROR "The checked-in icon and bundle resource are out of sync")
endif()
