use serde::{Deserialize, Serialize};

use crate::state::{
    AppState, BookmarkRecord, BrowserCommand, DownloadRecord, HistoryRecord, TabState, WindowState,
};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolResponse {
    pub version: u16,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    pub ok: bool,
    #[serde(flatten)]
    pub response: Response,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "result", rename_all = "camelCase")]
pub enum Response {
    AppSnapshot(AppState),
    TabsList(Vec<TabState>),
    WindowsList(Vec<WindowState>),
    BookmarksList(Vec<BookmarkRecord>),
    HistoryList(Vec<HistoryRecord>),
    DownloadsList(Vec<DownloadRecord>),
    CommandsList(Vec<BrowserCommand>),
    Json(serde_json::Value),
    Setting(Option<String>),
    /// A host-backed command has been accepted by FrostEngine but has not
    /// completed yet.  `operationId` is generated by Rust and is the sole
    /// correlation key for the eventual `host.operationCompleted` event.
    Operation(OperationResponse),
    /// A request that fan-outs to multiple independent host operations. Each
    /// entry has its own terminal event and callers must consider the batch
    /// failed when any entry completes unsuccessfully.
    Operations(Vec<OperationResponse>),
    Bool(bool),
    Error(String),
}

/// The immediate acknowledgement for an asynchronous host operation.
///
/// A protocol response with this payload is never a claim that the requested
/// browser operation succeeded.  Consumers must wait for the terminal event
/// carrying the same `operationId` before treating it as complete.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OperationResponse {
    pub operation_id: String,
    /// Compatibility-friendly explicit pending bit. `status` is retained as
    /// the extensible state field; native bridge code uses this bit to decide
    /// whether to retain a CEF callback until terminal completion.
    pub pending: bool,
    pub status: OperationStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum OperationStatus {
    Pending,
}

impl OperationResponse {
    pub fn pending(operation_id: impl Into<String>) -> Self {
        Self {
            operation_id: operation_id.into(),
            pending: true,
            status: OperationStatus::Pending,
        }
    }
}

impl ProtocolResponse {
    pub fn ok(id: Option<String>, response: Response) -> Self {
        Self {
            version: crate::PROTOCOL_VERSION,
            id,
            ok: true,
            response,
        }
    }

    pub fn error(id: Option<String>, message: impl Into<String>) -> Self {
        Self {
            version: crate::PROTOCOL_VERSION,
            id,
            ok: false,
            response: Response::Error(message.into()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn operation_response_is_an_explicit_pending_acknowledgement() {
        let response = ProtocolResponse::ok(
            Some("request-1".into()),
            Response::Operation(OperationResponse::pending("operation-1")),
        );

        assert_eq!(
            serde_json::to_value(response).unwrap(),
            serde_json::json!({
                "version": 0,
                "id": "request-1",
                "ok": true,
                "kind": "operation",
                "result": {
                    "operationId": "operation-1",
                    "pending": true,
                    "status": "pending"
                }
            })
        );
    }
}
